name: Generate assignment and solution versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-notebook:
    name: Generate assignment and solution versions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FG_MUDE_2025_token }}

      - name: Commit and push changes assignment version
        env:
          TOKEN: ${{ secrets.FG_MUDE_2025_token }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b assignment
          git merge origin/main
          git rm .github/workflows/generate-student-notebook.yml || true
          git rm requirements.txt || true
          git add .
          git commit -m "Update from main"
          git push origin assignment

      - name: Commit and push solution version
        env:
          TOKEN: ${{ secrets.FG_MUDE_2025_token }}
        run: |
          git checkout -b solution
          git merge origin/main
          git rm .github/workflows/generate-student-notebook.yml || true
          git rm requirements.txt || true
          git add .
          git commit -m "Remove requirements and workflow file from solution branch"
          git push origin solution --force
