name: Generate assignment and solution versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-notebook:
    name: Generate assignment and solution versions
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FG_MUDE_2025_token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Commit and push changes assignment version
        env:
          TOKEN: ${{ secrets.FG_MUDE_2025_token }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b assignment
          git merge origin/main
          git add .
          git commit -m "Generate assignment version"
          git rm .github/workflows/generate-student-notebook.yml
          git rm requirements.txt
          git add .
          git commit -m "Update from main"
          git push origin assignment
          fi

      - name: Commit and push solution version
        env:
          TOKEN: ${{ secrets.FG_MUDE_2025_token }}
        run: |
          git checkout -b solution
          git merge origin/main
          git add .
          git commit -m "Generate solution version"
          git rm .github/workflows/generate-student-notebook.yml
          git rm requirements.txt
          git add .
          git commit -m "Remove requirements and workflow file from solution branch"
          git push origin solution --force
          fi
